// src/pkg/emojiMap.ts

export const EMOJI_MAP: Record<string, string> = {
  gopher_confused: "/gophers_emojis/gopher-confused.png",
  gopher_crying_river: "/gophers_emojis/gopher-crying-river.png",
  gopher_crying: "/gophers_emojis/gopher-crying.png",
  gopher_dead: "/gophers_emojis/gopher-dead.png",
  gopher_expressionless: "/gophers_emojis/gopher-expressionless.png",
  gopher_eyeroll: "/gophers_emojis/gopher-eyeroll.gif",
  gopher_facepalm: "/gophers_emojis/gopher-facepalm.png",
  gopher_happy: "/gophers_emojis/gopher-happy.png",
  gopher_heart_eyes: "/gophers_emojis/gopher-heart-eyes.png",
  gopher_heart: "/gophers_emojis/gopher-heart.png",
  gopher_idea: "/gophers_emojis/gopher-idea.png",
  gopher_insomnia: "/gophers_emojis/gopher-insomnia.png",
  gopher_mind_blown: "/gophers_emojis/gopher-mind-blown.png",
  gopher_neutral: "/gophers_emojis/gopher-neutral.png",
  gopher_no_peeking: "/gophers_emojis/gopher-no-peeking.png",
  gopher_not_sure_if: "/gophers_emojis/gopher-not-sure-if.png",
  gopher_pirate: "/gophers_emojis/gopher-pirate.png",
  gopher_sad_sweat: "/gophers_emojis/gopher-sad-sweat.png",
  gopher_sad: "/gophers_emojis/gopher-sad.png",
  gopher_sick: "/gophers_emojis/gopher-sick.png",
  gopher_sleeping: "/gophers_emojis/gopher-sleeping.png",
  gopher_sleepy: "/gophers_emojis/gopher-sleepy.png",
  gopher_smiling_blushing: "/gophers_emojis/gopher-smiling-blushing.png",
  gopher_smiling_sweat: "/gophers_emojis/gopher-smiling-sweat.png",
  gopher_smiling: "/gophers_emojis/gopher-smiling.png",
  gopher_thinking: "/gophers_emojis/gopher-thinking.png",
  gopher_tired: "/gophers_emojis/gopher-tired.png",
  gopher_trying_hard: "/gophers_emojis/gopher-trying-hard.png",
  gopher_victorious: "/gophers_emojis/gopher-victorious.png",
  gopher_wink: "/gophers_emojis/gopher-wink.png",
  gopher_wondering: "/gophers_emojis/gopher-wondering.png",
};
